---
title: "Untitled"
author: "Han Yin"
date: "5/19/2020"
output: pdf_document
---

```{r setup knit, include=FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.pos = "H",
	fig.width = 5,
	fig.height = 3,
	message = FALSE,
	warning = FALSE,
	external = TRUE,
	echo = FALSE
)

library(tidyverse)
library(magrittr)
library(ggsci)
library(kableExtra)
library(plotly)

source("../scripts/functions.R")
```



```{r}
data <- 
  read.csv("../data/filledDatabaseNUMONLY_051820.csv") %>% 
  clean_data() %>% 
  filter(GroupCat %in% c(2,3:6))

table(data$X) %>% sort()
```


### Anion O

```{r}
subset <- data %>% filter(X == "O")
X <- subset[,-c(1:4)]
table(subset$GroupCat) %>% sort()

#### -------------   step 0: EDA   ------------- #### 

get_bars <- function(index){
  data.frame(
    group = subset$GroupCat,
    feature = X[,index]
  ) %>% 
    ggplot(aes(x = feature, fill = as.factor(group))) +
    geom_histogram(stat = "bin", bins = 30) +
    scale_fill_jco() +
    theme_minimal() + 
    labs(x = names(X)[index], 
         fill = 'Group')
}

library(cowplot)

layout_bars <- function(index){
  p1 = get_bars(index + 1)
  p2 = get_bars(index + 2)
  p3 = get_bars(index + 3)
  p4 = get_bars(index + 4)
  p5 = get_bars(index + 5)
  p6 = get_bars(index + 6)
  p7 = get_bars(index + 7)
  p8 = get_bars(index + 8)
  p9 = get_bars(index + 9)
  p10 = get_bars(index + 10)
  p11 = get_bars(index + 11)
  p12 = get_bars(index + 12)
  p13 = get_bars(index + 13)
  p14 = get_bars(index + 14)
  p15 = get_bars(index + 15)
  p16 = get_bars(index + 16)
  plot_grid(p1,p2,p3,
            p4,p5,p6,
            p7,p8,p9,
            p10,p11,p12,
            p13,p14,p15,p16, labels = "AUTO", ncol = 2)
}
```

```{r fig.height=20, fig.width=12}
layout_bars(0)
layout_bars(1)
layout_bars(3)
layout_bars(4)
```

```{r fig.height=2.5, fig.width=6}
get_bars(65)
```

