---
title: "Predictive Model"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup knit, include=FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.pos = "H",
	fig.width = 10,
	fig.height = 10,
	message = FALSE,
	warning = FALSE,
	external = TRUE,
	echo = FALSE
)

library(tidyverse)
library(magrittr)
library(ggsci)
library(kableExtra)

library(glmnet)
library(caret)

source("../scripts/functions.R")
```


```{r}
# load raw data files
# data <- read.csv("../data/filledDatabase.csv")[,-c(2:9,11:13)]
data <- read.csv("../data/filledDatabaseNUMONLY_042620.csv")

# clean data 
data <- clean_data(data) %>% collapse_data()

# separate compound and group_cate from the predictors
compound <- data$Compound
group_cat <- data$GroupCat

# prepare date for modeling
data <- select(data, -c("Compound"))
```


Overall
===================================== 

```{r}
X = data[,-c(1,2)] %>% remove_identical_cal() %>% as.matrix()
Y = data$GroupCat %>% as.matrix()
```

Column {.tabset}
-------------------------------------

### Ridge(1)

```{r} 
ridge_cv <- cv.glmnet(x = X, y = Y, alpha = 0, nfolds = 5, type.measure = "deviance", family = "multinomial") 

tb = 
  ridge_cv %>% 
  get_coef(tuning_parameter = ridge_cv$lambda.min) %>% 
  select(feature, Cubic, Tilted, Hexagonal, Others) %>% 
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), c(32,32)))
```


```{r} 
tb %>% filter(tag == 2) %>% select(-tag) %>% plot_coef()
```

### Ridge(2) 

```{r} 
tb %>% filter(tag == 1) %>% select(-tag) %>% plot_coef()
```


### LASSO(1)

```{r}
lasso_cv <- cv.glmnet(x = X, y = Y, alpha = 1, nfolds = 5, type.measure = "deviance", family = "multinomial")

tb = 
  lasso_cv %>% 
  get_coef(tuning_parameter = lasso_cv$lambda.min) %>% 
  select(feature, Cubic, Tilted, Hexagonal, Others) %>% 
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), c(32,32)))
```


```{r} 
tb %>% filter(tag == 2) %>% select(-tag) %>% plot_coef()
```

### LASSO(2)

```{r}
tb %>% filter(tag == 1) %>% select(-tag) %>% plot_coef()
```

### Elastic Net(1)

```{r}
elastic_cv <-
  train(GroupCat ~., data = data.frame(X,GroupCat=Y), method = "glmnet",
    trControl = trainControl("cv", number = 5),
    tuneLength = 10)

tb = 
  elastic_cv$finalModel %>%
  get_coef(tuning_parameter = elastic_cv$bestTune$lambda) %>%
  select(feature, Cubic, Tilted, Hexagonal, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), c(32,32)))
```

```{r}
tb %>% filter(tag == 2) %>% select(-tag) %>% plot_coef()
```

### Elastic Net(2)

```{r}
tb %>% filter(tag == 1) %>% select(-tag) %>% plot_coef()
```


Column {.tabset}
-------------------------------------
### Ridge

```{r}
folds = createFolds(1:nrow(X), k = 5, list = TRUE, returnTrain = FALSE)
tb_ridge = prediction_table(alpha = 0, lambda = ridge_cv$lambda.min) 
tb_ridge$r %>% print_accurate_tb()

tb_ridge$t %>% highlight_tb_count()
tb_ridge$t %>% highlight_tb_percent()
```

### LASSO

```{r}
tb_lasso = prediction_table(alpha = 1, lambda = lasso_cv$lambda.min)
tb_lasso$r %>% print_accurate_tb()

tb_lasso$t %>% highlight_tb_count()
tb_lasso$t %>% highlight_tb_percent()
```

### Elastic Net

```{r}
tb_elastic = prediction_table(alpha = elastic_cv$bestTune[[1]], lambda = elastic_cv$bestTune[[2]])
tb_elastic$r %>% print_accurate_tb()

tb_elastic$t %>% highlight_tb_count()
tb_elastic$t %>% highlight_tb_percent()
```


Anion O {data-icon="fa-signal"}
=====================================

```{r}
anion = "O"
X = data[data$X == anion,-c(1)] %>% remove_identical_cal() %>% as.matrix()
Y = data$GroupCat[data$X == anion] %>% as.matrix()
folds <- createFolds(1:nrow(X), k = 5, list = TRUE, returnTrain = FALSE)
```


Column {.tabset}
-------------------------------------
### Ridge(1)

```{r}
ridge_cv <- cv.glmnet(x = X, y = Y, alpha = 0, nfolds = 5, type.measure = "deviance", family = "multinomial")

tb = 
  ridge_cv %>%
  get_coef(tuning_parameter = ridge_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each = 34))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Ridge(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Ridge(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```


### LASSO(1)

```{r fig.height=20, fig.width=10}
lasso_cv <- cv.glmnet(x = X, y = Y, alpha = 1, nfolds = 5, type.measure = "deviance", family = "multinomial")

tb = 
  lasso_cv %>%
  get_coef(tuning_parameter = lasso_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each=34))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Lasso(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Lasso(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```


### Elastic Net(1)

```{r}
elastic_cv <-
  train(GroupCat ~., data = data.frame(X, GroupCat=Y), method = "glmnet",
    trControl = trainControl("cv", number = 5),
    tuneLength = 10)
tb =
  elastic_cv$finalModel %>%
  get_coef(tuning_parameter = elastic_cv$bestTune$lambda) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each=34))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Elastic Net(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Elastic Net(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```




Column {.tabset}
-------------------------------------
### Ridge

```{r}
tb_ridge = prediction_table(alpha = 0, lambda = ridge_cv$lambda.min)
tb_ridge$r %>% print_accurate_tb()

tb_ridge$t %>% highlight_tb_count()
tb_ridge$t %>% highlight_tb_percent()
```

### LASSO

```{r}
tb_lasso = prediction_table(alpha = 1, lambda = lasso_cv$lambda.min)
tb_lasso$r %>% print_accurate_tb()

tb_lasso$t %>% highlight_tb_count()
tb_lasso$t %>% highlight_tb_percent()
```

### Elastic Net

```{r}
tb_elastic = prediction_table(alpha = elastic_cv$bestTune[[1]], lambda = elastic_cv$bestTune[[2]])
tb_elastic$r %>% print_accurate_tb()

tb_elastic$t %>% highlight_tb_count()
tb_elastic$t %>% highlight_tb_percent()
```


Anion F {data-icon="fa-signal"}
=====================================

```{r}
anion = "F"
X = data[data$X == anion,-c(1,2)] %>% remove_identical_cal() %>% as.matrix()
Y = data$GroupCat[data$X == anion] %>% as.matrix()
folds <- createFolds(1:nrow(X), k = 5, list = TRUE, returnTrain = FALSE)
```


Column {.tabset}
-------------------------------------
### Ridge(1)

```{r fig.height=25, fig.width=10}
ridge_cv <- cv.glmnet(x = X, y = Y, alpha = 0, nfolds = 5, type.measure = "deviance", family = "multinomial")
tb = 
  ridge_cv %>%
  get_coef(tuning_parameter = ridge_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), each=44))
```

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Ridge(2)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```



### LASSO(1)

```{r fig.height=30, fig.width=10}
lasso_cv <- cv.glmnet(x = X, y = Y, alpha = 1, nfolds = 5, type.measure = "deviance", family = "multinomial")
tb =
  lasso_cv %>%
  get_coef(tuning_parameter = lasso_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), each=44))
```

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Lasso(2)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```




### Elastic Net(1)

```{r fig.height=30, fig.width=10}
elastic_cv <-
  train(GroupCat ~., data = data.frame(X,GroupCat=Y), method = "glmnet",
    trControl = trainControl("cv", number = 5),
    tuneLength = 10)
tb = 
  elastic_cv$finalModel %>%
  get_coef(tuning_parameter = elastic_cv$bestTune$lambda) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2), each=44))
```

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Elastic Net(2)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```



Column {.tabset}
-------------------------------------

### Ridge

```{r}
tb_ridge = prediction_table(alpha = 0, lambda = ridge_cv$lambda.min)
tb_ridge$r %>% print_accurate_tb()

tb_ridge$t %>% highlight_tb_count()
tb_ridge$t %>% highlight_tb_percent()
```

### LASSO

```{r}
tb_lasso = prediction_table(alpha = 1, lambda = lasso_cv$lambda.min)
tb_lasso$r %>% print_accurate_tb()

tb_lasso$t %>% highlight_tb_count()
tb_lasso$t %>% highlight_tb_percent()
```

### Elastic Net

```{r}
tb_elastic = prediction_table(alpha = elastic_cv$bestTune[[1]], lambda = elastic_cv$bestTune[[2]])
tb_elastic$r %>% print_accurate_tb()

tb_elastic$t %>% highlight_tb_count()
tb_elastic$t %>% highlight_tb_percent()
```


Other anions {data-icon="fa-signal"}
=====================================

```{r}
anion = c("O","F")
X = data[data$X != anion,-c(1,2)] %>% remove_identical_cal() %>% as.matrix()
Y = data$GroupCat[data$X != anion] %>% as.matrix()
folds <- createFolds(1:nrow(X), k = 5, list = TRUE, returnTrain = FALSE)
```


Column {.tabset}
-------------------------------------
### Ridge(1)

```{r}
ridge_cv <- cv.glmnet(x = X, y = Y, alpha = 0, nfolds = 5, type.measure = "deviance", family = "multinomial")

tb = 
  ridge_cv %>%
  get_coef(tuning_parameter = ridge_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each = 39))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Ridge(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Ridge(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```


### LASSO(1)

```{r fig.height=20, fig.width=10}
lasso_cv <- cv.glmnet(x = X, y = Y, alpha = 1, nfolds = 5, type.measure = "deviance", family = "multinomial")

tb = 
  lasso_cv %>%
  get_coef(tuning_parameter = lasso_cv$lambda.min) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each=39))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Lasso(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Lasso(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```


### Elastic Net(1)

```{r}
elastic_cv <-
  train(GroupCat ~., data = data.frame(X, GroupCat=Y), method = "glmnet",
    trControl = trainControl("cv", number = 5),
    tuneLength = 10)
tb =
  elastic_cv$finalModel %>%
  get_coef(tuning_parameter = elastic_cv$bestTune$lambda) %>%
  select(feature, Cubic, Tilted, Others) %>%
  filter(feature != "(Intercept)") %>%
  mutate(tag = rep(c(1,2,3), each=39))
```

```{r}
tb %>% filter(tag == 3) %>% plot_coef()
```

### Elastic Net(2)

```{r}
tb %>% filter(tag == 2) %>% plot_coef()
```

### Elastic Net(3)

```{r}
tb %>% filter(tag == 1) %>% plot_coef()
```




Column {.tabset}
-------------------------------------
### Ridge

```{r}
tb_ridge = prediction_table(alpha = 0, lambda = ridge_cv$lambda.min)
tb_ridge$r %>% print_accurate_tb()

tb_ridge$t %>% highlight_tb_count()
tb_ridge$t %>% highlight_tb_percent()
```

### LASSO

```{r}
tb_lasso = prediction_table(alpha = 1, lambda = lasso_cv$lambda.min)
tb_lasso$r %>% print_accurate_tb()

tb_lasso$t %>% highlight_tb_count()
tb_lasso$t %>% highlight_tb_percent()
```

### Elastic Net

```{r}
tb_elastic = prediction_table(alpha = elastic_cv$bestTune[[1]], lambda = elastic_cv$bestTune[[2]])
tb_elastic$r %>% print_accurate_tb()

tb_elastic$t %>% highlight_tb_count()
tb_elastic$t %>% highlight_tb_percent()
```


